spring:
  profiles:
    active: dev
camel:
  springboot:
    shutdownTimeout: 1
    health.indicator.enabled: true
management.security.enabled: false

info.app.name: Spring boiler plate
info.app.description: This is a Spring boot boiler plate code.
info.app.version: 1.0.0

---

spring:
  profiles: mock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: Prasad@1980
  mail:
    host: smtp.gmail.com
    port: 587
    username: prasaddusane1980@gmail.com
    password: pRASAD@1980
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mail.smtp.starttls.enable: true

mailto: prasaddusane1980@gmail.com
mailFrom: prasaddusane1980@gmail.com


message:   Hello from MOCK Profile
fromRoute: direct:input
toRoute: mock:output
healthRoute: direct:health
dbNode: mock:output1
selectNode: mock:output2

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: Prasad@1980
  mail:
    host: smtp.gmail.com
    port: 587
    username: prasaddusane1980@gmail.com
    password: pRASAD@1980
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: prasaddusane1980@gmail.com
mailFrom: prasaddusane1980@gmail.com
message:   Hello from DEV Profile
fromRoute: timer:restRoute?period=10s
toRoute:  http://localhost:8081/country
healthRoute: timer:health?period=10s
dbNode: jdbc:dataSource
selectNode: sql:select * from country where country_code = :#countryId?dataSource=#dataSource

---

spring:
  profiles: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: Prasad@1980
    mail:
      host: smtp.gmail.com
      port: 587
      username: prasaddusane1980@gmail.com
      password: pRASAD@1980
      properties.mail.smtp.auth:  true
      properties.mail.smtp.starttls.enable: true

  mailto: prasaddusane1980@gmail.com
  mailFrom: prasaddusane1980@gmail.com
  message:   Hello from DEV Profile
  fromRoute: timer:restRoute?period=10s
  toRoute:  http://localhost:8081/country
  healthRoute: timer:health?period=10s
  dbNode: jdbc:dataSource
  selectNode: sql:select * from country where country_code = :#countryId?dataSource=#dataSource


---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: Prasad@1980
    mail:
      host: smtp.gmail.com
      port: 587
      username: prasaddusane1980@gmail.com
      password: pRASAD@1980
      properties.mail.smtp.auth:  true
      properties.mail.smtp.starttls.enable: true

  mailto: prasaddusane1980@gmail.com
  mailFrom: prasaddusane1980@gmail.com
  message:   Hello from DEV Profile
  fromRoute: timer:restRoute?period=10s
  toRoute:  http://localhost:8081/country
  healthRoute: timer:health?period=10s
  dbNode: jdbc:dataSource
  selectNode: sql:select * from country where country_code = :#countryId?dataSource=#dataSource
---